In [36]:
import pandas as pd
from pathlib import Path
import numpy as np 

# Helper: safely sum coalition columns, treating missing parties as 0
def sum_existing_cols(df, cols):
    return df.reindex(columns=cols, fill_value=0).sum(axis=1)

def row_sum_existing_cols(df, cols):
    existing_cols = [col for col in cols if col in df.columns]
    
    if len(existing_cols) == 0:
        return pd.Series(0, index=df.index)
    
    return df[existing_cols].sum(axis=1, skipna=True)

# Chamber of Deputies Elections by Commune in 2018

commune_results_2018 = pd.read_csv(
    "/Users/hrishikroy/Downloads/camera-20180304/Camera2018_livComune.txt",
    sep=";",
    encoding="latin1")

commune_results_2018_pivoted = (commune_results_2018
    .pivot_table(
        index=["CIRCOSCRIZIONE", "COMUNE", "ELETTORI",
            "ELETTORI_MASCHI", "VOTANTI", "VOTANTI_MASCHI",
            "SCHEDE_BIANCHE"], columns="LISTA",
        values="VOTI_LISTA",
        aggfunc="sum",
        fill_value=0).reset_index())

commune_results_2018_pivoted.columns.name = None

commune_results_2018_pivoted.to_csv("/Users/hrishikroy/R Studio/Summer Research/data/commune_results_2018_pivoted.csv",
    index=False)



# Chamber of Deputies Elections by Commune in 2022


commune_results_2022 = pd.read_csv("/Users/hrishikroy/Downloads/camera-20220925/Camera_Italia_LivComune.csv",
    sep=";",
    decimal=",")

commune_results_2022_pivoted = (commune_results_2022
    .pivot_table(index=["CIRC-REG", "COMUNE", "ELETTORITOT", "ELETTORIM",
            "VOTANTITOT", "VOTANTIM", "SKBIANCHE"],
        columns="DESCRLISTA",
        values="VOTILISTA",
        aggfunc="sum",
        fill_value=0).reset_index())

commune_results_2022_pivoted.to_csv("/Users/hrishikroy/R Studio/Summer Research/data/commune_results_election_2022.csv",
    index=False)

In [16]:
commune_results_2018_pivoted

,CIRCOSCRIZIONE,COMUNE,ELETTORI,ELETTORI_MASCHI,VOTANTI,VOTANTI_MASCHI,SCHEDE_BIANCHE,+EUROPA,10 VOLTE MEGLIO,AUTODETERMINATZIONE,...,PARTITO VALORE UMANO,PATTO PER L'AUTONOMIA,PD-UV-UVP-EPAV,PER UNA SINISTRA RIVOLUZIONARIA,POTERE AL POPOLO!,POUR TOUS PER TUTTI PE TCHEUT,RINASCIMENTO MIR,RISPOSTA CIVICA,SIAMO,SVP - PATT
0,ABRUZZO,ABBATEGGIO,313,161,246,131,6,6.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
1,ABRUZZO,ACCIANO,273,145,184,107,2,2.0,0.0,0.0,...,6.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,ABRUZZO,AIELLI,1161,573,882,452,7,67.0,1.0,0.0,...,0.0,0.0,0.0,0.0,22.0,0.0,0.0,0.0,0.0,0.0
3,ABRUZZO,ALANNO,2855,1363,2188,1092,25,18.0,5.0,0.0,...,2.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0
4,ABRUZZO,ALBA ADRIATICA,9260,4450,6929,3387,71,77.0,6.0,0.0,...,11.0,0.0,0.0,0.0,54.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7981,VENETO 2,ZERMEGHEDO,980,489,807,401,11,21.0,1.0,0.0,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
7982,VENETO 2,ZEVIO,11053,5480,8788,4467,71,135.0,32.0,0.0,...,0.0,0.0,0.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0
7983,VENETO 2,ZIMELLA,3566,1763,2882,1453,32,22.0,11.0,0.0,...,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0
7984,VENETO 2,ZOVENCEDO,640,338,541,292,4,7.0,2.0,0.0,...,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0
7985,VENETO 2,ZUGLIANO,5389,2636,4417,2195,40,104.0,17.0,0.0,...,22.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0

In [17]:
commune_results_2022_pivoted

DESCRLISTA,CIRC-REG,COMUNE,ELETTORITOT,ELETTORIM,VOTANTITOT,VOTANTIM,SKBIANCHE,+EUROPA,ALLEANZA VERDI E SINISTRA,ALTERNATIVA PER L'ITALIA - NO GREEN PASS,...,MOVIMENTO 5 STELLE,NOI MODERATI/LUPI - TOTI - BRUGNARO - UDC,PARTITO ANIMALISTA - UCDL - 10 VOLTE MEGLIO,PARTITO COMUNISTA ITALIANO,PARTITO DELLA FOLLIA CREATIVA,PARTITO DEMOCRATICO - ITALIA DEMOCRATICA E PROGRESSISTA,SUD CHIAMA NORD,SUDTIROLER VOLKSPARTEI (SVP) - PATT,UNIONE POPOLARE CON DE MAGISTRIS,VITA
0,ABRUZZO,ABBATEGGIO,311,158,220,105,5,5,1,1,...,22,1,0,0,0,65,1,0,7,0
1,ABRUZZO,ACCIANO,233,124,142,80,2,2,0,1,...,10,1,0,0,0,29,0,0,1,7
2,ABRUZZO,AIELLI,1120,563,723,372,18,14,22,0,...,115,1,0,0,0,184,1,0,18,2
3,ABRUZZO,ALANNO,2795,1357,1877,938,53,18,26,3,...,255,5,0,0,0,297,1,0,20,5
4,ABRUZZO,ALBA ADRIATICA,9532,4541,5834,2878,100,108,136,15,...,1002,27,0,0,0,691,1,0,68,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7837,VENETO 2,ZERMEGHEDO,997,512,741,383,12,10,12,0,...,37,10,0,0,0,92,0,0,2,5
7838,VENETO 2,ZEVIO,11528,5701,8199,4114,75,196,190,0,...,462,103,0,0,0,896,0,0,65,135
7839,VENETO 2,ZIMELLA,3570,1786,2519,1278,40,37,36,0,...,111,31,0,0,0,229,0,0,26,36
7840,VENETO 2,ZOVENCEDO,672,353,479,254,4,11,16,0,...,24,3,0,0,0,37,0,0,5,19
7841,VENETO 2,ZUGLIANO,5472,2667,4030,1978,61,104,91,0,...,175,61,0,0,0,690,0,0,24,92

In [37]:
# Load 2018 election data

election_2018 = pd.read_csv("/Users/hrishikroy/R Studio/Summer Research/data/commune_results_election_2018.csv")

election_2018 = election_2018.iloc[:, :39]

# Check number of unique communes
election_2018["COMUNE"].nunique() 

for col in election_2018.columns:
    if col != "COMUNE":
        election_2018[col] = pd.to_numeric(election_2018[col], errors = "coerce")

election_2018_collapsed = (
    election_2018
    .groupby("COMUNE", as_index=False)
    .sum(numeric_only=True))

In [38]:
# Load CHES dataset and filter to Italy, 2019. I looked up the country number for Italy on the CHES codebook.

ches_dataset = pd.read_csv("/Users/hrishikroy/Downloads/ches_dataset.csv")

ches_dataset_italy = ches_dataset[ches_dataset["country"] == 8]

ches_dataset_italy_2019 = ches_dataset_italy[
    ches_dataset_italy["year"] == 2019]

In [39]:
# Party lookup table, I used ChatGPT for this part of the code because I needed help on 
# comparing the party names across the CHES and election datasets. 

party_lookup = pd.DataFrame({
    "party_id": [802,803,805,806,807,808,811,813,814,815,817,818,
        819,820,821,822,823,824,825,826,827,828,829,830,
        832,835,836,837,838,839,840,842,
        843,844,845,846,847,848,849,850],
    "party_full_name": [
        "Democratici di Sinistra",
        "Partito della Rifondazione Comunista",
        "Alleanza Nazionale",
        "Partito Repubblicano Italiano",
        "Partito Socialista Democratico Italiano",
        "Federazione dei Verdi",
        "Lega Nord",
        "Radicali Italiani",
        "Unione di Centro",
        "Forza Italia",
        "Unione Democratica",
        "Cristiani Democratici Uniti",
        "Democrazia è Libertà – La Margherita",
        "Lista Bonino",
        "Movimento Sociale Fiamma Tricolore",
        "Partito di Unità Proletaria",
        "Partito Popolare Italiano",
        "Partito Sardo d’Azione",
        "Rinnovamento Italiano",
        "Patto Segni",
        "Südtiroler Volkspartei",
        "Italia dei Valori",
        "Popolari-UDEUR",
        "Partito dei Pensionati",
        "Più Europa",
        "Nuovo Partito Socialista Italiano",
        "Partito dei Comunisti Italiani",
        "Partito Democratico",
        "Alleanza Verdi e Sinistra",
        "Partito Socialista Italiano",
        "Movimento per le Autonomie",
        "Sinistra Democratica",
        "Centro Democratico",
        "Fratelli d’Italia",
        "MoVimento Cinque Stelle",
        "Scelta Civica",
        "Vallée d’Aoste",
        "Nuovo Centrodestra",
        "Azione – Italia Viva",
        "Europa Verde"]})

In [40]:
# Merge CHES with party lookup
ches_party_full_name = ches_dataset_italy_2019.merge(
    party_lookup,
    on="party_id",
    how="left"
) 

ches_party_full_name

,year,country,eastwest,eumember,party_id,party,cmp_id,vote,seat,electionyear,...,antielite_salience,corrupt_salience,members_vs_leadership,executive_power,judicial_independence,mip_one,mip_two,mip_three,chesversion,party_full_name
0,2019,8,1,1,811,LN,32720.0,17.39,20.100000,2018,...,8.333333,3.375000,9.133333,NaN,NaN,NaN,NaN,NaN,2025.1,Lega Nord
1,2019,8,1,1,844,FdI,32630.0,4.35,5.000000,2018,...,8.000000,5.500000,8.357142,NaN,NaN,NaN,NaN,NaN,2025.1,Fratelli d’Italia
2,2019,8,1,1,827,SVP,32904.0,0.41,0.600000,2018,...,2.166667,4.600000,6.400000,NaN,NaN,NaN,NaN,NaN,2025.1,Südtiroler Volkspartei
3,2019,8,1,1,813,RI,NaN,NaN,NaN,2018,...,2.200000,5.615385,4.833334,NaN,NaN,NaN,NaN,NaN,2025.1,Radicali Italiani
4,2019,8,1,1,815,FI,32061.0,14.00,17.200001,2018,...,4.176471,2.466667,9.133333,NaN,NaN,NaN,NaN,NaN,2025.1,Forza Italia
5,2019,8,1,1,837,PD,32440.0,18.76,18.100000,2018,...,1.882353,5.333334,5.266667,NaN,NaN,NaN,NaN,NaN,2025.1,Partito Democratico
6,2019,8,1,1,838,SI,32230.0,3.39,2.300000,2018,...,3.785714,6.500000,5.333334,NaN,NaN,NaN,NaN,NaN,2025.1,Alleanza Verdi e Sinistra
7,2019,8,1,1,845,M5S,32956.0,33.33,36.700001,2018,...,8.888889,9.333333,4.266667,NaN,NaN,NaN,NaN,NaN,2025.1,MoVimento Cinque Stelle

In [41]:
# Standardize party name. Similar to above, I used ChatGPT for this part of the code because I needed help on 
# comparing the party names across the CHES and election datasets. 

conditions = [
    ches_party_full_name["party_full_name"].str.contains("CasaPound", na=False),
    ches_party_full_name["party_full_name"].str.contains("Popolo della Famiglia", na=False),
    ches_party_full_name["party_full_name"].str.contains("Noi con l'Italia", na=False),
    ches_party_full_name["party_full_name"].str.contains(r"^Lega$|Lega Nord", regex=True, na=False),
    ches_party_full_name["party_full_name"].str.contains("Forza Italia", na=False),
    ches_party_full_name["party_full_name"].str.contains("Fratelli", na=False),
    ches_party_full_name["party_full_name"].str.contains(r"Più Europa|\+Europa", regex=True, na=False),
    ches_party_full_name["party_full_name"].str.contains("Partito Democratico", na=False),
    ches_party_full_name["party_full_name"].str.contains("Italia Europa Insieme", na=False),
    ches_party_full_name["party_full_name"].str.contains("Civica Popolare", na=False),
    ches_party_full_name["party_full_name"].str.contains("Liberi e Uguali", na=False),
    ches_party_full_name["party_full_name"].str.contains("Valore Umano", na=False),
    ches_party_full_name["party_full_name"].str.contains("Potere al Popolo", na=False),
    ches_party_full_name["party_full_name"].str.contains("Cinque Stelle", na=False),
    ches_party_full_name["party_full_name"].str.contains("Italia agli Italiani", na=False),
    ches_party_full_name["party_full_name"].str.contains("Repubblicano Italiano", na=False),
    ches_party_full_name["party_full_name"].str.contains("10 Volte Meglio", na=False),
    ches_party_full_name["party_full_name"].str.contains("Sinistra Rivoluzionaria", na=False),
    ches_party_full_name["party_full_name"].str.contains("Grande Nord", na=False),
    ches_party_full_name["party_full_name"].str.contains("Blocco Nazionale", na=False),
    ches_party_full_name["party_full_name"].str.contains("Italia nel Cuore", na=False),
    ches_party_full_name["party_full_name"].str.contains("Rinascimento MIR", na=False),
    ches_party_full_name["party_full_name"].str.contains("Lista del Popolo", na=False),
    ches_party_full_name["party_full_name"].str.contains("Patto per l'Autonomia", na=False),
    ches_party_full_name["party_full_name"].str.contains(r"^SIAMO$", regex=True, na=False),
    ches_party_full_name["party_full_name"].str.contains(r"^Partito Comunista$", regex=True, na=False),
    ches_party_full_name["party_full_name"].str.contains("Autodeterminatzione", na=False),
    ches_party_full_name["party_full_name"].str.contains("Südtiroler Volkspartei", na=False),
    ches_party_full_name["party_full_name"].str.contains("PD-UV-UVP-EPAV", na=False),
    ches_party_full_name["party_full_name"].str.contains("Pour Tous", na=False),
    ches_party_full_name["party_full_name"].str.contains(r"Mov\.Nuova Valle d'Aosta|FRAT\. D'IT", regex=True, na=False),
    ches_party_full_name["party_full_name"].str.contains("Risposta Civica", na=False),
]

choices = [
    "CASAPOUND ITALIA",
    "IL POPOLO DELLA FAMIGLIA",
    "NOI CON L'ITALIA - UDC",
    "LEGA",
    "FORZA ITALIA",
    "FRATELLI D'ITALIA CON GIORGIA MELONI",
    "+EUROPA",
    "PARTITO DEMOCRATICO",
    "ITALIA EUROPA INSIEME",
    "CIVICA POPOLARE LORENZIN",
    "LIBERI E UGUALI",
    "PARTITO VALORE UMANO",
    "POTERE AL POPOLO!",
    "MOVIMENTO 5 STELLE",
    "ITALIA AGLI ITALIANI",
    "PARTITO REPUBBLICANO ITALIANO - ALA",
    "10 VOLTE MEGLIO",
    "PER UNA SINISTRA RIVOLUZIONARIA",
    "GRANDE NORD",
    "BLOCCO NAZIONALE PER LE LIBERTA'",
    "ITALIA NEL CUORE",
    "RINASCIMENTO MIR",
    "LISTA DEL POPOLO PER LA COSTITUZIONE",
    "PATTO PER L'AUTONOMIA",
    "SIAMO",
    "PARTITO COMUNISTA",
    "AUTODETERMINATZIONE",
    "SVP - PATT",
    "PD-UV-UVP-EPAV",
    "POUR TOUS PER TUTTI PE TCHEUT",
    "FI -FRAT. D'IT. -MOV.NUOVA VALLE D'AOSTA",
    "RISPOSTA CIVICA",
]

ches_party_full_name["party_standardized"] = np.select(
    conditions,
    choices,
    default = None
)

# Drop rows without standardized party names
ches_party_full_name = ches_party_full_name.dropna(subset=["party_standardized"]) 

# Create political position categories

ches_party_full_name["pol_position"] = np.select(
    [(ches_party_full_name["lrgen"] >= 0) & (ches_party_full_name["lrgen"] < 2.5),
        (ches_party_full_name["lrgen"] >= 2.5) & (ches_party_full_name["lrgen"] < 5),
        (ches_party_full_name["lrgen"] >= 5) & (ches_party_full_name["lrgen"] < 7.5),
        (ches_party_full_name["lrgen"] >= 7.5) & (ches_party_full_name["lrgen"] <= 10),],
    ["far-left",
        "centre-left",
        "centre-right",
        "far-right"],
    default = None) 

# Extract party lists by political category

far_left = ches_party_full_name.loc[
    ches_party_full_name["pol_position"] == "far-left",
    "party_standardized"
].tolist()

centre_left = ches_party_full_name.loc[
    ches_party_full_name["pol_position"] == "centre-left",
    "party_standardized"
].tolist()

centre_right = ches_party_full_name.loc[
    ches_party_full_name["pol_position"] == "centre-right",
    "party_standardized"
].tolist()

far_right = ches_party_full_name.loc[
    ches_party_full_name["pol_position"] == "far-right",
    "party_standardized"
].tolist() 

# Calculates total number of votes received by every block

election_2018_update_1 = election_2018_collapsed.copy()

election_2018_update_1["far_left_votes"] = row_sum_existing_cols(election_2018_update_1,
    far_left) 

election_2018_update_1["centre_left_votes"] = row_sum_existing_cols(
    election_2018_update_1,
    centre_left
)

election_2018_update_1["centre_right_votes"] = row_sum_existing_cols(
    election_2018_update_1,
    centre_right
)

election_2018_update_1["far_right_votes"] = row_sum_existing_cols(
    election_2018_update_1,
    far_right
) 

# Calculate vote shares

election_2018_update_1["far_left_votes_share"] = (
    election_2018_update_1["far_left_votes"] / election_2018_update_1["VOTANTI"]
) * 100

election_2018_update_1["centre_left_votes_share"] = (
    election_2018_update_1["centre_left_votes"] / election_2018_update_1["VOTANTI"]
) * 100

election_2018_update_1["centre_right_votes_share"] = (
    election_2018_update_1["centre_right_votes"] / election_2018_update_1["VOTANTI"]
) * 100

election_2018_update_1["far_right_votes_share"] = (
    election_2018_update_1["far_right_votes"] / election_2018_update_1["VOTANTI"]
) * 100 

# Export

election_2018_update_1.to_csv("election_2018_vote_share.csv", index=False)

/var/folders/j2/rsnnd9v53r981jkddsmqc6bw0000gn/T/ipykernel_43054/165904609.py:85: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ches_party_full_name["pol_position"] = np.select(

In [42]:
# Load 2022 election data 

election_2022 = pd.read_csv("/Users/hrishikroy/Downloads/commune_results_election_2022.csv")

# Keep first 30 columns, equivalent to election_2022[, 1:30] in R
election_2022 = election_2022.iloc[:, :30]

# Check number of unique communes
print(election_2022["COMUNE"].nunique())

# Make all non-COMUNE columns numeric where possible
for col in election_2022.columns:
    if col != "COMUNE":
        election_2022[col] = pd.to_numeric(election_2022[col], errors="coerce")

# Collapse by COMUNE, summing numeric columns
election_2022_collapsed = (
    election_2022
    .groupby("COMUNE", as_index=False)
    .sum(numeric_only=True)
)

# Load CHES dataset and filter to Italy, 2024

ches_dataset = pd.read_csv("/Users/hrishikroy/Downloads/ches_dataset.csv")

ches_dataset_italy = ches_dataset[ches_dataset["country"] == 8]

ches_dataset_italy_2024 = ches_dataset_italy[
    ches_dataset_italy["year"] == 2024
]

# Party lookup table. Similar to above, I used ChatGPT for this part of the code because I needed help on 
# comparing the party names across the CHES and election datasets.

party_lookup = pd.DataFrame({
    "party_id": [
        802,803,805,806,807,808,811,813,814,815,817,818,
        819,820,821,822,823,824,825,826,827,828,829,830,
        832,835,836,837,838,839,840,842,
        843,844,845,846,847,848,849,850
    ],
    "party_full_name": [
        "Democratici di Sinistra",
        "Partito della Rifondazione Comunista",
        "Alleanza Nazionale",
        "Partito Repubblicano Italiano",
        "Partito Socialista Democratico Italiano",
        "Federazione dei Verdi",
        "Lega Nord",
        "Radicali Italiani",
        "Unione di Centro",
        "Forza Italia",
        "Unione Democratica",
        "Cristiani Democratici Uniti",
        "Democrazia è Libertà – La Margherita",
        "Lista Bonino",
        "Movimento Sociale Fiamma Tricolore",
        "Partito di Unità Proletaria",
        "Partito Popolare Italiano",
        "Partito Sardo d’Azione",
        "Rinnovamento Italiano",
        "Patto Segni",
        "Südtiroler Volkspartei",
        "Italia dei Valori",
        "Popolari-UDEUR",
        "Partito dei Pensionati",
        "Più Europa",
        "Nuovo Partito Socialista Italiano",
        "Partito dei Comunisti Italiani",
        "Partito Democratico",
        "Alleanza Verdi e Sinistra",
        "Partito Socialista Italiano",
        "Movimento per le Autonomie",
        "Sinistra Democratica",
        "Centro Democratico",
        "Fratelli d’Italia",
        "MoVimento Cinque Stelle",
        "Scelta Civica",
        "Vallée d’Aoste",
        "Nuovo Centrodestra",
        "Azione – Italia Viva",
        "Europa Verde"]})

7824

In [43]:
# Merge CHES with party lookup
ches_party_full_name = ches_dataset_italy_2024.merge(
    party_lookup,
    on="party_id",
    how="left") 

ches_party_full_name

,year,country,eastwest,eumember,party_id,party,cmp_id,vote,seat,electionyear,...,antielite_salience,corrupt_salience,members_vs_leadership,executive_power,judicial_independence,mip_one,mip_two,mip_three,chesversion,party_full_name
0,2024,8,1,1,832,+E,NaN,2.83,0.500000,2022,...,1.000000,5.25,NaN,3.50,2.285714,NaN,NaN,NaN,2025.1,Più Europa
1,2024,8,1,1,844,FDI,NaN,25.98,30.600000,2022,...,7.166666,3.50,NaN,8.80,7.714286,NaN,NaN,NaN,2025.1,Fratelli d’Italia
2,2024,8,1,1,811,Lega,32720.0,8.79,17.000000,2022,...,7.666666,2.75,NaN,8.00,7.285714,NaN,NaN,NaN,2025.1,Lega Nord
3,2024,8,1,1,815,FI,32061.0,8.11,11.600000,2022,...,3.000000,1.00,NaN,7.50,7.285714,NaN,NaN,NaN,2025.1,Forza Italia
4,2024,8,1,1,850,EV,NaN,1.80,1.500000,2022,...,2.250000,6.50,NaN,1.75,1.166667,NaN,NaN,NaN,2025.1,Europa Verde
5,2024,8,1,1,845,MS5,NaN,15.43,13.400000,2022,...,7.500000,9.50,NaN,4.75,1.428572,NaN,NaN,NaN,2025.1,MoVimento Cinque Stelle
6,2024,8,1,1,849,A,NaN,7.78,5.400000,2022,...,1.600000,5.50,NaN,4.00,2.571429,NaN,NaN,NaN,2025.1,Azione – Italia Viva
7,2024,8,1,1,837,PD,32440.0,19.04,17.700001,2022,...,2.666667,5.25,NaN,3.00,1.857143,NaN,NaN,NaN,2025.1,Partito Democratico
8,2024,8,1,1,827,SVP,32904.0,0.42,0.800000,2022,...,0.333333,5.00,NaN,NaN,2.800000,NaN,NaN,NaN,2025.1,Südtiroler Volkspartei
9,2024,8,1,1,838,SI,32230.0,1.80,1.500000,2022,...,4.250000,6.75,NaN,1.40,1.166667,NaN,NaN,NaN,2025.1,Alleanza Verdi e Sinistra

In [44]:
# Standardize party names. Similar to above, I used ChatGPT for this part of the code because I needed help on 
# comparing the party names across the CHES and election datasets. 

conditions = [
    ches_party_full_name["party_full_name"].str.contains("Lega", na=False),
    ches_party_full_name["party_full_name"].str.contains("Forza Italia", na=False),
    ches_party_full_name["party_full_name"].str.contains("Fratelli", na=False),
    ches_party_full_name["party_full_name"].str.contains("Partito Democratico", na=False),
    ches_party_full_name["party_full_name"].str.contains("Alleanza Verdi", na=False),
    ches_party_full_name["party_full_name"].str.contains(r"Più Europa|\+Europa", regex=True, na=False),
    ches_party_full_name["party_full_name"].str.contains("Cinque Stelle", na=False),
    ches_party_full_name["party_full_name"].str.contains(r"Azione|Italia Viva", regex=True, na=False),
    ches_party_full_name["party_full_name"].str.contains("Italexit", na=False),
    ches_party_full_name["party_full_name"].str.contains("Unione Popolare", na=False),
    ches_party_full_name["party_full_name"].str.contains("Italia Sovrana", na=False),
    ches_party_full_name["party_full_name"].str.contains(r"Sudtirol|Südtirol", regex=True, na=False),]

choices = ["LEGA PER SALVINI PREMIER",
    "FORZA ITALIA",
    "FRATELLI D'ITALIA CON GIORGIA MELONI",
    "PARTITO DEMOCRATICO - ITALIA DEMOCRATICA E PROGRESSISTA",
    "ALLEANZA VERDI E SINISTRA",
    "+EUROPA",
    "MOVIMENTO 5 STELLE",
    "AZIONE - ITALIA VIVA - CALENDA",
    "ITALEXIT PER L'ITALIA",
    "UNIONE POPOLARE CON DE MAGISTRIS",
    "ITALIA SOVRANA E POPOLARE",
    "SUDTIROLER VOLKSPARTEI (SVP) - PATT"]

ches_party_full_name["party_standardized"] = np.select(
    conditions,
    choices,
    default=None)

# Drop rows without standardized party names
ches_party_full_name = ches_party_full_name.dropna(subset=["party_standardized"])

# Create political position categories. Again, these were based on the CHES codebook. 

ches_party_full_name["pol_position"] = np.select(
    [(ches_party_full_name["lrgen"] >= 0) & (ches_party_full_name["lrgen"] < 2.5),
        (ches_party_full_name["lrgen"] >= 2.5) & (ches_party_full_name["lrgen"] < 5),
        (ches_party_full_name["lrgen"] >= 5) & (ches_party_full_name["lrgen"] < 7.5),
        (ches_party_full_name["lrgen"] >= 7.5) & (ches_party_full_name["lrgen"] <= 10),],
    ["far-left",
        "centre-left",
        "centre-right",
        "far-right"],
    default=None
)

# Extract party lists by political category

far_left = ches_party_full_name.loc[ches_party_full_name["pol_position"] == "far-left",
    "party_standardized"].tolist()

centre_left = ches_party_full_name.loc[ches_party_full_name["pol_position"] == "centre-left",
    "party_standardized"].tolist()

centre_right = ches_party_full_name.loc[
    ches_party_full_name["pol_position"] == "centre-right",
    "party_standardized"
].tolist()

far_right = ches_party_full_name.loc[
    ches_party_full_name["pol_position"] == "far-right",
    "party_standardized"
].tolist()

# Sum votes by political bloc

election_2022_update_1 = election_2022_collapsed.copy()

election_2022_update_1["far_left_votes"] = row_sum_existing_cols(
    election_2022_update_1,
    far_left)

election_2022_update_1["centre_left_votes"] = row_sum_existing_cols(
    election_2022_update_1,
    centre_left)

election_2022_update_1["centre_right_votes"] = row_sum_existing_cols(
    election_2022_update_1,
    centre_right)

election_2022_update_1["far_right_votes"] = row_sum_existing_cols(
    election_2022_update_1,
    far_right)

# Calculate vote shares

election_2022_update_1["far_left_votes_share"] = (
    election_2022_update_1["far_left_votes"] / election_2022_update_1["VOTANTITOT"]) * 100

election_2022_update_1["centre_left_votes_share"] = (
    election_2022_update_1["centre_left_votes"] / election_2022_update_1["VOTANTITOT"]) * 100

election_2022_update_1["centre_right_votes_share"] = (
    election_2022_update_1["centre_right_votes"] / election_2022_update_1["VOTANTITOT"]) * 100

election_2022_update_1["far_right_votes_share"] = (
    election_2022_update_1["far_right_votes"] / election_2022_update_1["VOTANTITOT"]) * 100

# Export

election_2022_update_1.to_csv("election_2022_vote_share.csv", index=False)

/var/folders/j2/rsnnd9v53r981jkddsmqc6bw0000gn/T/ipykernel_43054/3716337256.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ches_party_full_name["pol_position"] = np.select(

In [45]:
# Renaming the column so that we can merge across the election datasets of 2018 and 2022
election_2022_update_1.rename(columns={"CIRC-REG": "CIRCOSCRIZIONE"}, inplace=True) 
election_2022_update_1

,COMUNE,CIRCOSCRIZIONE,ELETTORITOT,ELETTORIM,VOTANTITOT,VOTANTIM,SKBIANCHE,LEGA PER SALVINI PREMIER,FORZA ITALIA,NOI MODERATI/LUPI - TOTI - BRUGNARO - UDC,...,FORZA DEL POPOLO,SUDTIROLER VOLKSPARTEI (SVP) - PATT,far_left_votes,centre_left_votes,centre_right_votes,far_right_votes,far_left_votes_share,centre_left_votes_share,centre_right_votes_share,far_right_votes_share
0,ABANO TERME,0.0,15800,7472,11265,5437,123,1189,658,195,...,0,0,311,4003,658,4577,2.760763,35.534842,5.841101,40.630271
1,ABBADIA CERRETO,0.0,226,110,171,85,3,35,18,1,...,0,0,2,60,18,77,1.169591,35.087719,10.526316,45.029240
2,ABBADIA LARIANA,0.0,2643,1289,1846,905,37,233,115,15,...,0,0,88,627,115,727,4.767064,33.965330,6.229686,39.382449
3,ABBADIA SAN SALVATORE,0.0,4681,2246,3149,1588,50,252,113,5,...,0,0,108,1563,113,925,3.429660,49.634805,3.588441,29.374405
4,ABBASANTA,0.0,2181,1068,1222,614,19,64,95,14,...,0,0,45,442,95,415,3.682488,36.170213,7.774141,33.960720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7819,ZUGLIO,0.0,471,228,264,128,5,44,14,3,...,0,0,8,56,14,132,3.030303,21.212121,5.303030,50.000000
7820,ZUMAGLIA,0.0,817,393,554,275,12,62,38,5,...,0,0,23,159,38,258,4.151625,28.700361,6.859206,46.570397
7821,ZUMPANO,0.0,2014,982,1228,617,21,70,141,1,...,0,0,13,688,141,256,1.058632,56.026059,11.482085,20.846906
7822,ZUNGOLI,0.0,854,412,482,248,21,68,32,1,...,0,0,5,247,32,116,1.037344,51.244813,6.639004,24.066390
7823,ZUNGRI,0.0,1538,767,738,360,26,52,158,6,...,1,0,8,225,158,247,1.084011,30.487805,21.409214,33.468835

In [56]:
election_2018

,COMUNE,CIRCOSCRIZIONE,ELETTORI,ELETTORI_MASCHI,VOTANTI,VOTANTI_MASCHI,SCHEDE_BIANCHE,+EUROPA,10 VOLTE MEGLIO,AUTODETERMINATZIONE,...,SIAMO,SVP - PATT,far_left_votes,centre_left_votes,centre_right_votes,far_right_votes,far_left_coalition_perc_18,centre_left_coalition_perc_18,centre_right_coalition_perc_18,far_right_coalition_perc_18
0,ABANO TERME,0.0,15576,7331,12359,5944,134,343.0,47.0,0.0,...,0.0,0.0,0,5046.0,1408.0,3793.0,0.0,40.828546,11.392507,30.690185
1,ABBADIA CERRETO,0.0,232,110,198,97,2,1.0,0.0,0.0,...,0.0,0.0,0,80.0,23.0,71.0,0.0,40.404040,11.616162,35.858586
2,ABBADIA LARIANA,0.0,2598,1268,2062,1015,44,54.0,2.0,0.0,...,0.0,0.0,0,821.0,207.0,578.0,0.0,39.815713,10.038797,28.031038
3,ABBADIA SAN SALVATORE,0.0,4957,2340,3766,1876,50,76.0,0.0,0.0,...,0.0,0.0,0,2121.0,296.0,660.0,0.0,56.319703,7.859798,17.525226
4,ABBASANTA,0.0,2240,1103,1521,757,10,18.0,0.0,30.0,...,0.0,0.0,0,799.0,227.0,250.0,0.0,52.531229,14.924392,16.436555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7946,ZUGLIO,0.0,494,244,346,175,5,5.0,2.0,0.0,...,0.0,0.0,0,137.0,17.0,123.0,0.0,39.595376,4.913295,35.549133
7947,ZUMAGLIA,0.0,869,412,676,322,13,26.0,0.0,0.0,...,0.0,0.0,0,217.0,100.0,232.0,0.0,32.100592,14.792899,34.319527
7948,ZUMPANO,0.0,1964,960,1485,773,13,7.0,0.0,0.0,...,0.0,0.0,0,767.0,181.0,78.0,0.0,51.649832,12.188552,5.252525
7949,ZUNGOLI,0.0,933,454,668,346,18,1.0,3.0,0.0,...,0.0,0.0,0,380.0,50.0,47.0,0.0,56.886228,7.485030,7.035928
7950,ZUNGRI,0.0,1593,782,1085,540,36,8.0,0.0,0.0,...,0.0,0.0,0,463.0,289.0,113.0,0.0,42.672811,26.635945,10.414747

In [57]:
# Renaming the dataframes so that they are easier to work with
election_2018 = election_2018_update_1 
election_2022 = election_2022_update_1 

# Renaming the columns so that they can be distinguished after merging 
election_2022.rename(columns={"centre_right_votes_share": "centre_right_coalition_perc_22"}, inplace=True) 
election_2018.rename(columns={"centre_right_votes_share": "centre_right_coalition_perc_18"}, inplace=True) 

election_2022.rename(columns={"centre_left_votes_share": "centre_left_coalition_perc_22"}, inplace=True) 
election_2018.rename(columns={"centre_left_votes_share": "centre_left_coalition_perc_18"}, inplace=True) 

election_2022.rename(columns={"far_right_votes_share": "far_right_coalition_perc_22"}, inplace=True) 
election_2018.rename(columns={"far_right_votes_share": "far_right_coalition_perc_18"}, inplace=True) 

election_2022.rename(columns={"far_left_votes_share": "far_left_coalition_perc_22"}, inplace=True) 
election_2018.rename(columns={"far_left_votes_share": "far_left_coalition_perc_18"}, inplace=True)

In [58]:
# Merging the two data frames 
merged_elections = election_2018.merge(
    election_2022,
    on = ["CIRCOSCRIZIONE", "COMUNE"],
    how = "left") 

#merged_elections

,COMUNE,CIRCOSCRIZIONE,ELETTORI,ELETTORI_MASCHI,VOTANTI,VOTANTI_MASCHI,SCHEDE_BIANCHE,+EUROPA_x,10 VOLTE MEGLIO,AUTODETERMINATZIONE,...,FORZA DEL POPOLO,SUDTIROLER VOLKSPARTEI (SVP) - PATT,far_left_votes_y,centre_left_votes_y,centre_right_votes_y,far_right_votes_y,far_left_coalition_perc_22,centre_left_coalition_perc_22,centre_right_coalition_perc_22,far_right_coalition_perc_22
0,ABANO TERME,0.0,15576,7331,12359,5944,134,343.0,47.0,0.0,...,0.0,0.0,311.0,4003.0,658.0,4577.0,2.760763,35.534842,5.841101,40.630271
1,ABBADIA CERRETO,0.0,232,110,198,97,2,1.0,0.0,0.0,...,0.0,0.0,2.0,60.0,18.0,77.0,1.169591,35.087719,10.526316,45.029240
2,ABBADIA LARIANA,0.0,2598,1268,2062,1015,44,54.0,2.0,0.0,...,0.0,0.0,88.0,627.0,115.0,727.0,4.767064,33.965330,6.229686,39.382449
3,ABBADIA SAN SALVATORE,0.0,4957,2340,3766,1876,50,76.0,0.0,0.0,...,0.0,0.0,108.0,1563.0,113.0,925.0,3.429660,49.634805,3.588441,29.374405
4,ABBASANTA,0.0,2240,1103,1521,757,10,18.0,0.0,30.0,...,0.0,0.0,45.0,442.0,95.0,415.0,3.682488,36.170213,7.774141,33.960720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7946,ZUGLIO,0.0,494,244,346,175,5,5.0,2.0,0.0,...,0.0,0.0,8.0,56.0,14.0,132.0,3.030303,21.212121,5.303030,50.000000
7947,ZUMAGLIA,0.0,869,412,676,322,13,26.0,0.0,0.0,...,0.0,0.0,23.0,159.0,38.0,258.0,4.151625,28.700361,6.859206,46.570397
7948,ZUMPANO,0.0,1964,960,1485,773,13,7.0,0.0,0.0,...,0.0,0.0,13.0,688.0,141.0,256.0,1.058632,56.026059,11.482085,20.846906
7949,ZUNGOLI,0.0,933,454,668,346,18,1.0,3.0,0.0,...,0.0,0.0,5.0,247.0,32.0,116.0,1.037344,51.244813,6.639004,24.066390
7950,ZUNGRI,0.0,1593,782,1085,540,36,8.0,0.0,0.0,...,1.0,0.0,8.0,225.0,158.0,247.0,1.084011,30.487805,21.409214,33.468835

In [60]:
# Calculating the difference between percentage of votes won by each bloc in 2018 and 2022

merged_elections["centre_left_change_22_18"] = (merged_elections["centre_left_coalition_perc_22"] 
    - merged_elections["centre_left_coalition_perc_18"])

merged_elections["centre_right_change_22_18"] = (merged_elections["centre_right_coalition_perc_22"] 
    - merged_elections["centre_right_coalition_perc_18"]) 

merged_elections["far_right_change_22_18"] = (merged_elections["far_right_coalition_perc_22"] 
    - merged_elections["far_right_coalition_perc_18"]) 

merged_elections["far_left_change_22_18"] = (merged_elections["far_left_coalition_perc_22"] 
    - merged_elections["far_left_coalition_perc_18"]) 

merged_elections

,COMUNE,CIRCOSCRIZIONE,ELETTORI,ELETTORI_MASCHI,VOTANTI,VOTANTI_MASCHI,SCHEDE_BIANCHE,+EUROPA_x,10 VOLTE MEGLIO,AUTODETERMINATZIONE,...,centre_right_votes_y,far_right_votes_y,far_left_coalition_perc_22,centre_left_coalition_perc_22,centre_right_coalition_perc_22,far_right_coalition_perc_22,centre_left_change_22_18,centre_right_change_22_18,far_right_change_22_18,far_left_change_22_18
0,ABANO TERME,0.0,15576,7331,12359,5944,134,343.0,47.0,0.0,...,658.0,4577.0,2.760763,35.534842,5.841101,40.630271,-5.293704,-5.551407,9.940085,2.760763
1,ABBADIA CERRETO,0.0,232,110,198,97,2,1.0,0.0,0.0,...,18.0,77.0,1.169591,35.087719,10.526316,45.029240,-5.316321,-1.089846,9.170654,1.169591
2,ABBADIA LARIANA,0.0,2598,1268,2062,1015,44,54.0,2.0,0.0,...,115.0,727.0,4.767064,33.965330,6.229686,39.382449,-5.850382,-3.809111,11.351411,4.767064
3,ABBADIA SAN SALVATORE,0.0,4957,2340,3766,1876,50,76.0,0.0,0.0,...,113.0,925.0,3.429660,49.634805,3.588441,29.374405,-6.684898,-4.271357,11.849179,3.429660
4,ABBASANTA,0.0,2240,1103,1521,757,10,18.0,0.0,30.0,...,95.0,415.0,3.682488,36.170213,7.774141,33.960720,-16.361017,-7.150251,17.524165,3.682488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7946,ZUGLIO,0.0,494,244,346,175,5,5.0,2.0,0.0,...,14.0,132.0,3.030303,21.212121,5.303030,50.000000,-18.383255,0.389736,14.450867,3.030303
7947,ZUMAGLIA,0.0,869,412,676,322,13,26.0,0.0,0.0,...,38.0,258.0,4.151625,28.700361,6.859206,46.570397,-3.400231,-7.933694,12.250870,4.151625
7948,ZUMPANO,0.0,1964,960,1485,773,13,7.0,0.0,0.0,...,141.0,256.0,1.058632,56.026059,11.482085,20.846906,4.376227,-0.706467,15.594380,1.058632
7949,ZUNGOLI,0.0,933,454,668,346,18,1.0,3.0,0.0,...,32.0,116.0,1.037344,51.244813,6.639004,24.066390,-5.641414,-0.846026,17.030462,1.037344
7950,ZUNGRI,0.0,1593,782,1085,540,36,8.0,0.0,0.0,...,158.0,247.0,1.084011,30.487805,21.409214,33.468835,-12.185006,-5.226731,23.054088,1.084011